# Generated by Django 4.2.5 on 2023-11-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["last_name"],
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                default="default_prof.png",
                upload_to="profiles/%Y/%m/%d",
                verbose_name="Photo",
            ),
        ),
    ]
