# Generated by Django 4.2.5 on 2024-01-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_exercisetype_alter_exercise_options_and_more"),
        ("profiles", "0002_alter_profile_options_profile_email_profile_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="Score"
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(
                        default=False,
                        help_text="the result of module taken",
                        verbose_name="Passed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="courses.module",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_results",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Result",
                "verbose_name_plural": "Module Results",
            },
        ),
    ]
