version: '3.9'

services:
  redis:
    container_name: redis
    image: redis:7
    command: --port 6379
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  db:
    image: postgres:14.5
    container_name: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: -p ${DB_PORT}
    depends_on:
      - redis
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5555:80
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data: