# Generated by Django 4.2.5 on 2023-11-02 20:52

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category name"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"verbose_name": "Module", "verbose_name_plural": "Modules"},
        ),
        migrations.RemoveField(
            model_name="module",
            name="overview",
        ),
        migrations.AddField(
            model_name="course",
            name="images",
            field=models.ImageField(
                default="default.png", upload_to="course/", verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="module",
            name="images",
            field=models.ImageField(
                blank=True,
                default="default.png",
                null=True,
                upload_to="modules/%Y/%m/%d",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_category",
                to="courses.category",
            ),
        ),
    ]
