# Generated by Django 4.2.5 on 2023-11-19 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_category_alter_course_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["course"],
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
            },
        ),
        migrations.AlterField(
            model_name="exercise",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_module",
                to="courses.module",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_module",
                to="courses.course",
            ),
        ),
    ]
