# Generated by Django 4.2.5 on 2023-12-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_module_options_alter_exercise_module_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="ex_type",
            field=models.CharField(
                choices=[("watch", "watch"), ("read", "read"), ("quiz", "quiz")],
                max_length=20,
                verbose_name="Type Of Exercise",
            ),
        ),
    ]
