# Generated by Django 4.2.5 on 2024-01-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_exercise_ex_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Type name")),
            ],
            options={
                "verbose_name_plural": "Exercise types",
            },
        ),
        migrations.AlterModelOptions(
            name="exercise",
            options={"verbose_name": "Exercise", "verbose_name_plural": "Exercises"},
        ),
        migrations.AlterField(
            model_name="exercise",
            name="ex_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="courses.exercisetype"
            ),
        ),
    ]
