# Generated by Django 4.2.5 on 2024-01-02 14:39

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_exercisetype_alter_exercise_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="description",
        ),
        migrations.RemoveField(
            model_name="module",
            name="content",
        ),
        migrations.AddField(
            model_name="exercise",
            name="content",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Content"
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="ex_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.exercisetype"
            ),
        ),
    ]
