# Generated by Django 4.2.5 on 2024-01-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_remove_exercise_description_remove_module_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.TextField(default="English", verbose_name="Language"),
        ),
    ]
