name: Django CI
env:
  SECRET_KEY: "31$4q&8(be8g1tzflg5gs-l-etav2v9#bdovky1*$j7+_7scjn"
  DEBUG: True
  TIME_ZONE: "Europe/Minsk"
  ENGINE: "django.db.backends.postgresql"
  NAME: "postgres"
  USER: "postgres"
  PASSWORD: "postgres"
  HOST: "localhost"
  PORT: 5432
on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mkdir logs
    - name: Run Tests
      run: |
        pytest
